services:
  aria2:
    container_name: aria2
    image: p3terx/aria2-pro
    environment:
      - UMASK_SET=022
      - RPC_SECRET=${RPC_SECRET}
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=256M
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Shanghai
      - SPECIAL_MODE=move
    volumes:
      - ${CONF_FOLDER}:/config
      - ${DL_FOLDER}:/downloads
    network_mode: bridge
    ports:
      - 6200:6800
      - 6288:6888
      - 6288:6888/udp
    restart: unless-stopped
    logging:
      driver: none
